name: Matrix Build and ECR Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [docker-image-1, docker-image-2, docker-image-3, docker-image-4, docker-image-5]
        ecr_uri: [${{ secrets.ECR_URI_1 }}, ${{ secrets.ECR_URI_2 }}, ${{ secrets.ECR_URI_3 }}, ${{ secrets.ECR_URI_4 }}, ${{ secrets.ECR_URI_5 }}]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.app }}
          file: ./${{ matrix.app }}/Dockerfile
          push: true
          tags: ${{ matrix.ecr_uri }}:latest
